CREATE EXTENSION IF NOT EXISTS citext;
CREATE TABLE IF NOT EXISTS user_project (
  nickname VARCHAR(128) UNIQUE NOT NULL,
  password VARCHAR(128)        NOT NULL,
  email    CITEXT UNIQUE       NOT NULL PRIMARY KEY,
  wins     INT DEFAULT 0,
  losses    INT DEFAULT 0,
  draws   INT DEFAULT 0
);